title: "DRAGEN pipeline report"
subtitle: "Best-practice workflow for clinical SNP calling using DRAGEN"
custom_logo: "ikmblogo.png"
custom_logo_title: "Insitute of Clinical Molecular Biology, Kiel"
custom_logo_url: "http://www.ikmb.uni-kiel.de"

extra_fn_clean_exts:
    - type: regex
      pattern: "_S[0-9]+_L00.*"
    - type: truncate
      pattern: ".hard-filtered"
    - type: truncate
      pattern: "_R1"
    - type: truncate
      pattern : "_R2"
    - type: truncate
      pattern: "_duplicate_metrics.txt"

report_comment: >
    This report has been generated automatically by the IKMB DRAGEN pipeline.
    For help interpreting the outputs, please see: https://github.com/ikmb/dragen-variant-calling

report_header_info:
    - Contact E-mail: "b.loescher@ikmb.uni-kiel.de"
    - Application Type: "Clinical variant calling"

top_modules:
    - 'general_stats'
    - 'dragen_usage'
    - 'picard'
    - 'picard_hsmetrics'
    - 'bcftools'
