title: "Exome pipeline report"
subtitle: "Best-practice workflow for clinical SNP calling"
custom_logo: "ikmblogo.png"
custom_logo_title: "Insitute of Clinical Molecular Biology, Kiel"
custom_logo_url: "http://www.ikmb.uni-kiel.de"

extra_fn_clean_exts:
    - _R1
    - _R2
    - _duplicate_metrics.txt

report_comment: >
    This report has been generated automatically by the IKMB Diagnostic Exome pipeline.
    For help interpreting the outputs, please see: https://github.com/ikmb/exome-seq

report_header_info:
    - Contact E-mail: "b.loescher@ikmb.uni-kiel.de"
    - Application Type: "Whole exome sequencing"

top_modules:
    - 'general_stats'
    - 'picard'
    - 'picard_hsmetrics'
    - 'bcftools'
    - 'sex_check'
